export const scenarios = [
  { level: 1, title: 'One-word recall', category: 'Simple · trivia',
    prompt: 'Answer with only one word: what is the capital of France?' },
  { level: 2, title: 'Tiny translation', category: 'Simple · language',
    prompt: "Translate 'good morning' into Spanish. Respond only with the translation, no explanation." },
  { level: 3, title: 'Arithmetic word problem', category: 'Simple · math',
    prompt: 'A shirt costs 40 dollars and is on sale at 25 percent off. What is the final price? Answer with just the number.' },
  { level: 4, title: 'Two-bullet summary', category: 'Medium · summarize',
    prompt: 'Summarize the following in exactly two short bullets. Text: "Remote work increases flexibility but reduces spontaneous collaboration. Companies report higher productivity but lower team cohesion. Managers say communication requires more discipline."' },
  { level: 5, title: 'Small Python utility', category: 'Medium · code',
    prompt: 'Write a Python function flatten(nested_list) that flattens exactly one level of nesting. Include a short docstring and one usage example. No unit tests, no explanation.' },
  { level: 6, title: 'SQL join and aggregate', category: 'Medium · data',
    prompt: 'Given two tables orders(id, customer_id, amount, created_at) and customers(id, name, country), write a SQL query that returns the top 5 countries by total order amount in the last 30 days. Return one query, no explanation.' },
  { level: 7, title: 'Concept comparison', category: 'Medium · explain',
    prompt: 'Explain the practical difference between UDP and TCP for a junior developer in three short bullets. Include one example workload for each.' },
  { level: 8, title: 'Rate-limiting subsystem', category: 'Complex · design',
    prompt: 'Design a rate-limiting subsystem for a public REST API that receives 50,000 requests per second across 10 regions. Cover: algorithm choice with justification, per-user vs per-tenant vs global limits, distributed counter coordination and its consistency tradeoffs, handling of legitimate burst traffic during a sale, and observability signals you would emit. Provide concrete numbers where relevant.' },
  { level: 9, title: 'Constrained delivery plan', category: 'Complex · plan',
    prompt: 'You have 6 weeks to migrate 25 microservices from AWS ECS to Kubernetes with zero customer downtime, a team of 3 engineers, a $50,000 infrastructure budget, and a mandatory security review at end of week 4. Produce a phased plan with the critical path, the top 5 risks with mitigations, and a concrete fallback if the security review fails. Include an estimated engineer-day breakdown per phase.' },
  { level: 10, title: 'Distributed system debugging', category: 'Complex · diagnose',
    prompt: 'A distributed API shows normal average CPU and database latency, but p99 latency spikes every 15 minutes across all regions. Give a ranked list of at least 6 hypotheses, the discriminating signal you would gather for each, and the order in which you would investigate. Explicitly rule out at least two hypotheses using cheap evidence.' },
  { level: 11, title: 'Thread-safe LRU cache', category: 'Complex · code',
    prompt: 'Implement a thread-safe LRU cache class in Java called ConcurrentLruCache<K, V> with configurable capacity, get(K), put(K, V), and size() methods. Prefer bounded lock scope and avoid unbounded synchronized regions. Explain in one short paragraph why your locking choices are correct. Include a small usage example.' },
  { level: 12, title: 'Mathematical proof', category: 'Very complex · reasoning',
    prompt: 'Prove or disprove: for every integer n greater than 1, the harmonic sum 1 + 1/2 + 1/3 + ... + 1/n is never an integer. Show the argument step by step, state any lemmas you rely on, and identify where the proof would break if applied to n = 1.' },
  { level: 13, title: 'Global cost optimization', category: 'Very complex · optimization',
    prompt: 'A global SaaS platform runs on 3 clouds across 12 regions with a 99.99 percent SLO, data residency requirements in the EU and India, and a 10x traffic spike expected during a scheduled sale. Current spend is 2 million dollars per month. Devise a cost-optimization strategy that maintains the SLO, respects residency, absorbs the spike, and quantifies the tradeoffs of each choice. Propose specific numbers for reserved capacity, spot usage, cross-region failover, data-tier changes, and expected monthly savings.' },
  { level: 14, title: 'Constrained algorithm design', category: 'Very complex · algorithm',
    prompt: 'You are given a weighted directed graph with up to 200,000 nodes and 1,000,000 edges. Some edges have negative weights but there are no negative cycles. Given a start node and up to 50 forbidden node sequences (each of length 2 or 3) that a valid path may not contain in that order, design an algorithm that finds the shortest path to every other node while respecting the forbidden sequences. State the time complexity, space complexity, and correctness argument. Provide clear pseudocode.' },
  { level: 15, title: 'Conflict-resolving synthesis', category: 'Very complex · synthesis',
    prompt: 'You are a review board deciding between event sourcing and state-based persistence for a regulated global payments ledger. Requirements conflict: regulators require a full immutable audit trail, engineering needs sub-100ms p99 read latency, security needs cryptographic non-repudiation, operations needs a 4-hour RPO across regions, and finance needs provable balance reconciliation on demand. Compare both approaches across all five dimensions, explicitly resolve each conflict, make a defensible recommendation, and describe two failure scenarios where your recommendation could still fail along with how you would detect and recover from each.' }
];
